// this is generated by LLM.
#ifndef OS_H
#define OS_H

#if !defined(_WIN32)
    #if !defined(_POSIX_C_SOURCE)
        #define _POSIX_C_SOURCE 200809L
    #endif
    #if !defined(_DEFAULT_SOURCE)
        #define _DEFAULT_SOURCE 1
    #endif
#endif

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <time.h>
#include <errno.h>

#ifdef _WIN32
    #include <windows.h>
    #include <direct.h>
    #include <process.h>
    #include <io.h>
    #pragma comment(lib, "ws2_32.lib")
    #define OS_SEP "\\"
    #define OS_SEP_CHAR '\\'
    #define OS_NAME "windows"
    #define OS_PATHMAX MAX_PATH
#else
    #include <unistd.h>
    #include <dirent.h>
    #include <sys/stat.h>
    #include <sys/types.h>
    #include <sys/utsname.h>
    #include <pwd.h>
    #include <fcntl.h>
    #include <limits.h>
    #define OS_SEP "/"
    #define OS_SEP_CHAR '/'
    #define OS_PATHMAX PATH_MAX
    #ifdef __APPLE__
        #define OS_NAME "darwin"
        #include <sys/sysctl.h>
    #else
        #define OS_NAME "linux"
    #endif
#endif

#ifndef OS_COPY_BUF
#define OS_COPY_BUF 65536
#endif

static inline int os_lasterr(void) {
#ifdef _WIN32
    return (int)GetLastError();
#else
    return errno;
#endif
}


#define os_path_join(out,size,...) os_path__join(out,size,__VA_ARGS__,NULL)


static inline char *os_getcwd(char *buf, int size) {
    if (!buf || size <= 0) return NULL;
#ifdef _WIN32
    return _getcwd(buf, size);
#else
    return getcwd(buf, size);
#endif
}

static inline int os_chdir(const char *path) {
    if (!path) return -1;
#ifdef _WIN32
    return _chdir(path);
#else
    return chdir(path);
#endif
}

static inline int os_mkdir(const char *path) {
    if (!path) return -1;
#ifdef _WIN32
    return _mkdir(path);
#else
    return mkdir(path, 0755);
#endif
}

static inline int os_makedirs(const char *path) {
    if (!path) return -1;
    char tmp[OS_PATHMAX];
    int n = snprintf(tmp, sizeof(tmp), "%s", path);
    if (n <= 0 || n >= (int)sizeof(tmp)) return -1;
    for (int i = 1; i < n; i++) {
        if (tmp[i] == OS_SEP_CHAR || tmp[i] == '/') {
            tmp[i] = '\0';
            os_mkdir(tmp);
            tmp[i] = OS_SEP_CHAR;
        }
    }
    return os_mkdir(tmp);
}

static inline int os_rename(const char *src, const char *dst) {
    if (!src || !dst) return -1;
    return rename(src, dst);
}

static inline int os_exists(const char *path) {
    if (!path) return 0;
#ifdef _WIN32
    return _access(path, 0) == 0;
#else
    return access(path, F_OK) == 0;
#endif
}

static inline int os_isfile(const char *path) {
    if (!path) return 0;
#ifdef _WIN32
    DWORD a = GetFileAttributesA(path);
    return (a != INVALID_FILE_ATTRIBUTES && !(a & FILE_ATTRIBUTE_DIRECTORY));
#else
    struct stat s;
    return (stat(path, &s) == 0 && S_ISREG(s.st_mode));
#endif
}

static inline int os_isdir(const char *path) {
    if (!path) return 0;
#ifdef _WIN32
    DWORD a = GetFileAttributesA(path);
    return (a != INVALID_FILE_ATTRIBUTES && (a & FILE_ATTRIBUTE_DIRECTORY));
#else
    struct stat s;
    return (stat(path, &s) == 0 && S_ISDIR(s.st_mode));
#endif
}

static inline int os_islink(const char *path) {
    if (!path) return 0;
#ifdef _WIN32
    DWORD a = GetFileAttributesA(path);
    return (a != INVALID_FILE_ATTRIBUTES && (a & FILE_ATTRIBUTE_REPARSE_POINT));
#else
    struct stat s;
    return (lstat(path, &s) == 0 && S_ISLNK(s.st_mode));
#endif
}

static inline long long os_filesize(const char *path) {
    if (!path) return -1;
#ifdef _WIN32
    struct _stat64 s;
    return (_stat64(path, &s) == 0) ? (long long)s.st_size : -1LL;
#else
    struct stat s;
    return (stat(path, &s) == 0) ? (long long)s.st_size : -1LL;
#endif
}

static inline long long os_mtime(const char *path) {
    if (!path) return -1;
#ifdef _WIN32
    struct _stat64 s;
    return (_stat64(path, &s) == 0) ? (long long)s.st_mtime : -1LL;
#else
    struct stat s;
    return (stat(path, &s) == 0) ? (long long)s.st_mtime : -1LL;
#endif
}

static inline int os_copy(const char *src, const char *dst) {
    if (!src || !dst) return -1;
#ifdef _WIN32
    return CopyFileA(src, dst, FALSE) ? 0 : -1;
#else
    int r = -1;
    int fi = open(src, O_RDONLY);
    if (fi < 0) return -1;
    struct stat s;
    if (fstat(fi, &s) < 0) { close(fi); return -1; }
    int fo = open(dst, O_WRONLY | O_CREAT | O_TRUNC, s.st_mode & 0777);
    if (fo < 0) { close(fi); return -1; }
    char *buf = (char *)malloc(OS_COPY_BUF);
    if (!buf) { close(fi); close(fo); return -1; }
    ssize_t n;
    r = 0;
    while ((n = read(fi, buf, OS_COPY_BUF)) > 0) {
        if (write(fo, buf, (size_t)n) != n) { r = -1; break; }
    }
    if (n < 0) r = -1;
    free(buf);
    close(fi);
    close(fo);
    return r;
#endif
}

static inline char *os_realpath(const char *path, char *out, int size) {
    if (!path || !out || size <= 0) return NULL;
#ifdef _WIN32
    return GetFullPathNameA(path, (DWORD)size, out, NULL) ? out : NULL;
#else
    char tmp[OS_PATHMAX];
    if (!realpath(path, tmp)) return NULL;
    if ((int)strlen(tmp) >= size) return NULL;
    strcpy(out, tmp);
    return out;
#endif
}

static inline int os_symlink(const char *target, const char *link) {
    if (!target || !link) return -1;
#ifdef _WIN32
    DWORD flags = os_isdir(target) ? SYMBOLIC_LINK_FLAG_DIRECTORY : 0;
    return CreateSymbolicLinkA(link, target, flags) ? 0 : -1;
#else
    return symlink(target, link);
#endif
}

static inline int os_readlink(const char *path, char *out, int size) {
    if (!path || !out || size <= 0) return -1;
#ifdef _WIN32
    (void)path; (void)out; (void)size;
    return -1;
#else
    ssize_t n = readlink(path, out, (size_t)(size - 1));
    if (n < 0) return -1;
    out[n] = '\0';
    return 0;
#endif
}

static inline char *os_getenv(const char *name) {
    if (!name) return NULL;
    return getenv(name);
}

static inline const char *os_getenv_def(const char *name, const char *def) {
    if (!name) return def;
    char *v = getenv(name);
    return v ? v : def;
}

static inline int os_setenv(const char *name, const char *val) {
    if (!name || !val) return -1;
#ifdef _WIN32
    char buf[4096];
    if (snprintf(buf, sizeof(buf), "%s=%s", name, val) >= (int)sizeof(buf)) return -1;
    return _putenv(buf);
#else
    return setenv(name, val, 1);
#endif
}

static inline int os_unsetenv(const char *name) {
    if (!name) return -1;
#ifdef _WIN32
    char buf[256];
    if (snprintf(buf, sizeof(buf), "%s=", name) >= (int)sizeof(buf)) return -1;
    return _putenv(buf);
#else
    return unsetenv(name);
#endif
}

static inline int os_system(const char *cmd) {
    if (!cmd) return -1;
    return system(cmd);
}

static inline int os_getpid(void) {
#ifdef _WIN32
    return (int)GetCurrentProcessId();
#else
    return (int)getpid();
#endif
}

static inline int os_getppid(void) {
#ifdef _WIN32
    return -1;
#else
    return (int)getppid();
#endif
}

static inline void os_sleep(int ms) {
    if (ms < 0) return;
#ifdef _WIN32
    Sleep((DWORD)ms);
#else
    usleep((useconds_t)ms * 1000);
#endif
}

static inline long long os_time_ms(void) {
#ifdef _WIN32
    FILETIME ft;
    GetSystemTimeAsFileTime(&ft);
    long long t = ((long long)ft.dwHighDateTime << 32) | ft.dwLowDateTime;
    return (t - 116444736000000000LL) / 10000;
#else
    struct timespec ts;
    clock_gettime(CLOCK_REALTIME, &ts);
    return (long long)ts.tv_sec * 1000LL + ts.tv_nsec / 1000000LL;
#endif
}

static inline long long os_monotonic_ms(void) {
#ifdef _WIN32
    return (long long)GetTickCount64();
#else
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000LL + ts.tv_nsec / 1000000LL;
#endif
}

static inline int os_cpu_count(void) {
#ifdef _WIN32
    SYSTEM_INFO si;
    GetSystemInfo(&si);
    return (int)si.dwNumberOfProcessors;
#elif defined(__APPLE__)
    int n = 0;
    size_t sz = sizeof(n);
    sysctlbyname("hw.logicalcpu", &n, &sz, NULL, 0);
    return n > 0 ? n : 1;
#else
    int n = (int)sysconf(_SC_NPROCESSORS_ONLN);
    return n > 0 ? n : 1;
#endif
}

static inline long long os_total_mem(void) {
#ifdef _WIN32
    MEMORYSTATUSEX ms;
    ms.dwLength = sizeof(ms);
    GlobalMemoryStatusEx(&ms);
    return (long long)ms.ullTotalPhys;
#elif defined(__APPLE__)
    long long n = 0;
    size_t sz = sizeof(n);
    sysctlbyname("hw.memsize", &n, &sz, NULL, 0);
    return n;
#else
    long pages = sysconf(_SC_PHYS_PAGES);
    long pgsz  = sysconf(_SC_PAGE_SIZE);
    return (pages > 0 && pgsz > 0) ? (long long)pages * pgsz : -1LL;
#endif
}

static inline char *os_homedir(void) {
#ifdef _WIN32
    char *h = getenv("USERPROFILE");
    return h ? h : getenv("HOMEDRIVE");
#else
    char *h = getenv("HOME");
    if (h) return h;
    struct passwd *pw = getpwuid(getuid());
    return pw ? pw->pw_dir : NULL;
#endif
}

static inline char *os_tmpdir(void) {
#ifdef _WIN32
    char *t = getenv("TEMP");
    return t ? t : getenv("TMP");
#else
    char *t = getenv("TMPDIR");
    return t ? t : "/tmp";
#endif
}

static inline int os_path__join(char *out, int size, ...) {
    if (!out || size <= 0) return -1;
    va_list ap;
    va_start(ap, size);
    int w = 0, i = 0;
    const char *p;
    while ((p = va_arg(ap, const char *))) {
        if (i++ > 0) {
            if (w >= size - 1) { va_end(ap); return -1; }
            out[w++] = OS_SEP[0];
        }
        int n = snprintf(out + w, size - w, "%s", p);
        if (n < 0 || n >= size - w) { va_end(ap); return -1; }
        w += n;
    }
    va_end(ap);
    return 0;
}

static inline const char *os_path_basename(const char *path) {
    if (!path) return NULL;
    const char *s = strrchr(path, OS_SEP_CHAR);
#ifdef _WIN32
    const char *s2 = strrchr(path, '/');
    if (s2 > s) s = s2;
#endif
    return s ? s + 1 : path;
}

static inline int os_path_dirname(char *out, int size, const char *path) {
    if (!out || !path || size <= 0) return -1;
    const char *s = strrchr(path, OS_SEP_CHAR);
#ifdef _WIN32
    const char *s2 = strrchr(path, '/');
    if (s2 > s) s = s2;
#endif
    if (!s) { strncpy(out, ".", size); out[size-1] = '\0'; return 0; }
    int len = (int)(s - path);
    if (len == 0) len = 1;
    if (len >= size) return -1;
    strncpy(out, path, len);
    out[len] = '\0';
    return 0;
}

static inline const char *os_path_ext(const char *path) {
    if (!path) return "";
    const char *b = os_path_basename(path);
    if (!b) return "";
    const char *d = strrchr(b, '.');
    return d ? d : "";
}

static inline int os_path_isabs(const char *path) {
    if (!path) return 0;
#ifdef _WIN32
    return (path[0] && path[1] == ':') || path[0] == '\\' || path[0] == '/';
#else
    return path[0] == '/';
#endif
}

static inline char *os_read_file(const char *path, long long *out_size) {
    if (!path) return NULL;
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return NULL; }
    long long sz = (long long)ftell(f);
    if (sz < 0) { fclose(f); return NULL; }
    rewind(f);
    char *buf = (char *)malloc((size_t)(sz + 1));
    if (!buf) { fclose(f); return NULL; }
    if ((long long)fread(buf, 1, (size_t)sz, f) != sz) {
        free(buf); fclose(f); return NULL;
    }
    buf[sz] = '\0';
    if (out_size) *out_size = sz;
    fclose(f);
    return buf;
}

static inline int os_write_file(const char *path, const void *data, long long size) {
    if (!path || !data || size < 0) return -1;
    FILE *f = fopen(path, "wb");
    if (!f) return -1;
    int r = ((long long)fwrite(data, 1, (size_t)size, f) == size) ? 0 : -1;
    fclose(f);
    return r;
}

static inline int os_append_file(const char *path, const void *data, long long size) {
    if (!path || !data || size < 0) return -1;
    FILE *f = fopen(path, "ab");
    if (!f) return -1;
    int r = ((long long)fwrite(data, 1, (size_t)size, f) == size) ? 0 : -1;
    fclose(f);
    return r;
}

static inline void os_uname(char *out, int size) {
    if (!out || size <= 0) return;
#ifdef _WIN32
    OSVERSIONINFOEXA v;
    memset(&v, 0, sizeof(v));
    v.dwOSVersionInfoSize = sizeof(v);
    GetVersionExA((OSVERSIONINFOA *)&v);
    snprintf(out, size, "Windows %lu.%lu.%lu", v.dwMajorVersion, v.dwMinorVersion, v.dwBuildNumber);
#else
    struct utsname u;
    if (uname(&u) == 0)
        snprintf(out, size, "%s %s %s %s", u.sysname, u.release, u.version, u.machine);
    else
        strncpy(out, "unknown", size);
    out[size-1] = '\0';
#endif
}

static inline void os_hostname(char *out, int size) {
    if (!out || size <= 0) return;
#ifdef _WIN32
    DWORD s = (DWORD)size;
    if (!GetComputerNameA(out, &s)) out[0] = '\0';
#else
    if (gethostname(out, (size_t)size) != 0) out[0] = '\0';
    out[size-1] = '\0';
#endif
}

typedef struct {
    char name[OS_PATHMAX];
    int is_dir;
    long long size;
    long long mtime;
} os_dirent;

typedef struct {
#ifdef _WIN32
    HANDLE h;
    WIN32_FIND_DATAA fd;
    int first;
    char base[OS_PATHMAX];
#else
    DIR *d;
    char base[OS_PATHMAX];
#endif
} os_dir;

static inline int os_dir_open(os_dir *d, const char *path) {
    if (!d || !path) return 0;
#ifdef _WIN32
    char pat[OS_PATHMAX];
    if (snprintf(pat, sizeof(pat), "%s\\*", path) >= (int)sizeof(pat)) return 0;
    d->h = FindFirstFileA(pat, &d->fd);
    d->first = 1;
    strncpy(d->base, path, sizeof(d->base)-1);
    d->base[sizeof(d->base)-1] = '\0';
    return d->h != INVALID_HANDLE_VALUE;
#else
    d->d = opendir(path);
    strncpy(d->base, path, sizeof(d->base)-1);
    d->base[sizeof(d->base)-1] = '\0';
    return d->d != NULL;
#endif
}

static inline int os_dir_read(os_dir *d, os_dirent *e) {
    if (!d || !e) return 0;
#ifdef _WIN32
    if (d->first) {
        d->first = 0;
    } else {
        if (!FindNextFileA(d->h, &d->fd)) return 0;
    }
    strncpy(e->name, d->fd.cFileName, sizeof(e->name)-1);
    e->name[sizeof(e->name)-1] = '\0';
    e->is_dir = (d->fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) != 0;
    ULARGE_INTEGER ui;
    ui.LowPart  = d->fd.nFileSizeLow;
    ui.HighPart = d->fd.nFileSizeHigh;
    e->size = (long long)ui.QuadPart;
    ULARGE_INTEGER ft;
    ft.LowPart  = d->fd.ftLastWriteTime.dwLowDateTime;
    ft.HighPart = d->fd.ftLastWriteTime.dwHighDateTime;
    e->mtime = (long long)((ft.QuadPart - 116444736000000000ULL) / 10000000ULL);
    return 1;
#else
    struct dirent *de;
    while ((de = readdir(d->d)) != NULL) {
        if (strcmp(de->d_name, ".") == 0 || strcmp(de->d_name, "..") == 0) continue;
        strncpy(e->name, de->d_name, sizeof(e->name)-1);
        e->name[sizeof(e->name)-1] = '\0';
        char full[OS_PATHMAX];
        snprintf(full, sizeof(full), "%s/%s", d->base, de->d_name);
        struct stat s;
        if (stat(full, &s) == 0) {
            e->is_dir = S_ISDIR(s.st_mode);
            e->size   = (long long)s.st_size;
            e->mtime  = (long long)s.st_mtime;
        } else {
            e->is_dir = de->d_type == DT_DIR;
            e->size   = -1;
            e->mtime  = -1;
        }
        return 1;
    }
    return 0;
#endif
}

static inline void os_dir_close(os_dir *d) {
    if (!d) return;
#ifdef _WIN32
    if (d->h != INVALID_HANDLE_VALUE) FindClose(d->h);
#else
    if (d->d) { closedir(d->d); d->d = NULL; }
#endif
}

#endif
